class ProficiencyManager:
    def __init__(self):
        # Define proficiency charts for various character classes
        self.proficiency_data = {
            'Warrior': {
                1: {'weapon': 4, 'nonweapon': 3},
                2: {'weapon': 4, 'nonweapon': 3},
                3: {'weapon': 5, 'nonweapon': 4},
                4: {'weapon': 5, 'nonweapon': 4},
                5: {'weapon': 5, 'nonweapon': 4},
                6: {'weapon': 6, 'nonweapon': 5},
                7: {'weapon': 6, 'nonweapon': 5},
                8: {'weapon': 6, 'nonweapon': 5},
                9: {'weapon': 7, 'nonweapon': 6},
                10: {'weapon': 7, 'nonweapon': 6},
                11: {'weapon': 7, 'nonweapon': 6},
                12: {'weapon': 8, 'nonweapon': 7},
                13: {'weapon': 8, 'nonweapon': 7},
                14: {'weapon': 8, 'nonweapon': 7},
                15: {'weapon': 9, 'nonweapon': 8},
                16: {'weapon': 9, 'nonweapon': 8},
                17: {'weapon': 9, 'nonweapon': 8},
                18: {'weapon': 10, 'nonweapon': 9},
                19: {'weapon': 10, 'nonweapon': 9},
                20: {'weapon': 10, 'nonweapon': 9},
            },
            'Berserker_Runecaster': {
                1: {'weapon': 2, 'nonweapon': 3},
                2: {'weapon': 2, 'nonweapon': 3},
                3: {'weapon': 3, 'nonweapon': 4},
                4: {'weapon': 3, 'nonweapon': 4},
                5: {'weapon': 3, 'nonweapon': 4},
                6: {'weapon': 4, 'nonweapon': 5},
                7: {'weapon': 4, 'nonweapon': 5},
                8: {'weapon': 4, 'nonweapon': 5},
                9: {'weapon': 5, 'nonweapon': 6},
                10: {'weapon': 5, 'nonweapon': 6},
                11: {'weapon': 5, 'nonweapon': 6},
                12: {'weapon': 6, 'nonweapon': 7},
                13: {'weapon': 6, 'nonweapon': 7},
                14: {'weapon': 6, 'nonweapon': 7},
                15: {'weapon': 7, 'nonweapon': 8},
                16: {'weapon': 7, 'nonweapon': 8},
                17: {'weapon': 7, 'nonweapon': 8},
                18: {'weapon': 8, 'nonweapon': 9},
                19: {'weapon': 8, 'nonweapon': 9},
                20: {'weapon': 8, 'nonweapon': 9},
            },
            'Rogue': {
                1: {'weapon': 2, 'nonweapon': 3},
                2: {'weapon': 2, 'nonweapon': 3},
                3: {'weapon': 2, 'nonweapon': 3},
                4: {'weapon': 3, 'nonweapon': 4},
                5: {'weapon': 3, 'nonweapon': 4},
                6: {'weapon': 3, 'nonweapon': 4},
                7: {'weapon': 3, 'nonweapon': 4},
                8: {'weapon': 4, 'nonweapon': 5},
                9: {'weapon': 4, 'nonweapon': 5},
                10: {'weapon': 4, 'nonweapon': 5},
                11: {'weapon': 4, 'nonweapon': 5},
                12: {'weapon': 5, 'nonweapon': 6},
                13: {'weapon': 5, 'nonweapon': 6},
                14: {'weapon': 5, 'nonweapon': 6},
                15: {'weapon': 5, 'nonweapon': 6},
                16: {'weapon': 6, 'nonweapon': 7},
                17: {'weapon': 6, 'nonweapon': 7},
                18: {'weapon': 6, 'nonweapon': 7},
                19: {'weapon': 6, 'nonweapon': 7},
                20: {'weapon': 7, 'nonweapon': 8},
            },
            'Priest': {
                1: {'weapon': 2, 'nonweapon': 4},
                2: {'weapon': 2, 'nonweapon': 4},
                3: {'weapon': 2, 'nonweapon': 5},
                4: {'weapon': 3, 'nonweapon': 5},
                5: {'weapon': 3, 'nonweapon': 5},
                6: {'weapon': 3, 'nonweapon': 6},
                7: {'weapon': 3, 'nonweapon': 6},
                8: {'weapon': 4, 'nonweapon': 6},
                9: {'weapon': 4, 'nonweapon': 7},
                10: {'weapon': 4, 'nonweapon': 7},
                11: {'weapon': 4, 'nonweapon': 7},
                12: {'weapon': 5, 'nonweapon': 8},
                13: {'weapon': 5, 'nonweapon': 8},
                14: {'weapon': 5, 'nonweapon': 8},
                15: {'weapon': 5, 'nonweapon': 9},
                16: {'weapon': 6, 'nonweapon': 9},
                17: {'weapon': 6, 'nonweapon': 9},
                18: {'weapon': 6, 'nonweapon': 10},
                19: {'weapon': 6, 'nonweapon': 10},
                20: {'weapon': 7, 'nonweapon': 10},
            },
            'Wizard': {
                1: {'weapon': 1, 'nonweapon': 4},
                2: {'weapon': 1, 'nonweapon': 4},
                3: {'weapon': 1, 'nonweapon': 5},
                4: {'weapon': 1, 'nonweapon': 5},
                5: {'weapon': 1, 'nonweapon': 5},
                6: {'weapon': 2, 'nonweapon': 6},
                7: {'weapon': 2, 'nonweapon': 6},
                8: {'weapon': 2, 'nonweapon': 6},
                9: {'weapon': 2, 'nonweapon': 7},
                10: {'weapon': 2, 'nonweapon': 7},
                11: {'weapon': 2, 'nonweapon': 7},
                12: {'weapon': 3, 'nonweapon': 8},
                13: {'weapon': 3, 'nonweapon': 8},
                14: {'weapon': 3, 'nonweapon': 8},
                15: {'weapon': 3, 'nonweapon': 9},
                16: {'weapon': 3, 'nonweapon': 9},
                17: {'weapon': 3, 'nonweapon': 9},
                18: {'weapon': 4, 'nonweapon': 10},
                19: {'weapon': 4, 'nonweapon': 10},
                20: {'weapon': 4, 'nonweapon': 10},
            },
            'Psionicist': {
                1: {'weapon': 2, 'nonweapon': 3},
                2: {'weapon': 2, 'nonweapon': 3},
                3: {'weapon': 2, 'nonweapon': 4},
                4: {'weapon': 2, 'nonweapon': 4},
                5: {'weapon': 3, 'nonweapon': 4},
                6: {'weapon': 3, 'nonweapon': 5},
                7: {'weapon': 3, 'nonweapon': 5},
                8: {'weapon': 3, 'nonweapon': 5},
                9: {'weapon': 3, 'nonweapon': 6},
                10: {'weapon': 4, 'nonweapon': 6},
                11: {'weapon': 4, 'nonweapon': 6},
                12: {'weapon': 4, 'nonweapon': 7},
                13: {'weapon': 4, 'nonweapon': 7},
                14: {'weapon': 4, 'nonweapon': 7},
                15: {'weapon': 5, 'nonweapon': 8},
                16: {'weapon': 5, 'nonweapon': 8},
                17: {'weapon': 5, 'nonweapon': 8},
                18: {'weapon': 5, 'nonweapon': 9},
                19: {'weapon': 5, 'nonweapon': 9},
                20: {'weapon': 6, 'nonweapon': 9}
            }
        }

    def get_proficiency_slots(self, character_class, level):
        # Return the proficiency slots for a specific class and level
        return self.proficiency_data.get(character_class, {}).get(level, {'weapon': 0, 'nonweapon': 0})